apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: karpenter-nodepool
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: karpenter-nodepool
    spec:
      project: default
      source:
        repoURL: '{{metadata.annotations.gitops_karpenter_url}}'
        path: '{{metadata.annotations.gitops_karpenter_path}}'
        targetRevision: '{{metadata.annotations.gitops_karpenter_revision}}'
        directory:
          recurse: false
      destination:
        namespace: default
        name: '{{name}}'
      syncPolicy:
        automated:
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 60
